# This is a basic workflow to help you get started with Actions

name: Start bot from python

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      bot_token:
          description: 'Telegram Bot Token'
          required: true
env:
  TZ: Asia/Kolkata
  BOT_TOKEN: ${{ github.event.inputs.bot_token }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: starting bot
        run: |
          sudo chmod +x install.sh
          sudo ./install.sh
          python g.py

      - name: Keep the bot active
        run: sleep $((15 * 60))

      
